# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.plotWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.plotWidget.setObjectName("plotWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.amplitudeBodePlot = QtWidgets.QWidget(self.tab)
        self.amplitudeBodePlot.setMinimumSize(QtCore.QSize(500, 0))
        self.amplitudeBodePlot.setMaximumSize(QtCore.QSize(166674, 16777215))
        self.amplitudeBodePlot.setObjectName("amplitudeBodePlot")
        self.gridLayout_3.addWidget(self.amplitudeBodePlot, 0, 0, 1, 1)
        self.phaseBode = QtWidgets.QWidget(self.tab)
        self.phaseBode.setMinimumSize(QtCore.QSize(500, 0))
        self.phaseBode.setObjectName("phaseBode")
        self.gridLayout_3.addWidget(self.phaseBode, 1, 0, 1, 1)
        self.visualConfWidget = QtWidgets.QWidget(self.tab)
        self.visualConfWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.visualConfWidget.setObjectName("visualConfWidget")
        self.gridLayout_3.addWidget(self.visualConfWidget, 0, 1, 2, 1)
        self.plotWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.visualConfWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.visualConfWidget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.visualConfWidget_2.setObjectName("visualConfWidget_2")
        self.gridLayout_4.addWidget(self.visualConfWidget_2, 0, 1, 2, 1)
        self.temporalResponsePlot = QtWidgets.QWidget(self.tab_2)
        self.temporalResponsePlot.setMinimumSize(QtCore.QSize(500, 0))
        self.temporalResponsePlot.setMaximumSize(QtCore.QSize(166674, 16777215))
        self.temporalResponsePlot.setObjectName("temporalResponsePlot")
        self.gridLayout_4.addWidget(self.temporalResponsePlot, 0, 0, 2, 1)
        self.plotWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.zeroesPolesPlot = QtWidgets.QWidget(self.tab_3)
        self.zeroesPolesPlot.setObjectName("zeroesPolesPlot")
        self.gridLayout_5.addWidget(self.zeroesPolesPlot, 0, 0, 1, 1)
        self.plotWidget.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.plotWidget, 1, 0, 1, 1)
        self.functionsList = QtWidgets.QListWidget(self.centralwidget)
        self.functionsList.setMinimumSize(QtCore.QSize(150, 0))
        self.functionsList.setMaximumSize(QtCore.QSize(200, 600))
        self.functionsList.setObjectName("functionsList")
        self.gridLayout_2.addWidget(self.functionsList, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.plotWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plotWidget.setTabText(self.plotWidget.indexOf(self.tab), _translate("MainWindow", "Bode"))
        self.plotWidget.setTabText(self.plotWidget.indexOf(self.tab_2), _translate("MainWindow", "Respuesta Temporal"))
        self.plotWidget.setTabText(self.plotWidget.indexOf(self.tab_3), _translate("MainWindow", "Polos y Ceros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
